### PR TITLE
Add a few 2019 talks to news page

### PR DESCRIPTION
**Pull request by lukpueh**
- 10/14/19: Tobias Furuholm at CASTOR Software Days (+ slides)
Thanks for promoting in-toto and sharing your resources,  @furuholm!

- 06/08/19: Lukas at MiniDebConf Hamburg
- 05/22/19: Justin and Lukas at KubeCon Europe

### CODE REVIEW

**Comment by lukpueh** [comment]
@SantiagoTorres, @JustinCappos, were there more talks/events in 2019 that we should add to the news section?

**Comment by JustinCappos** [comment]
Do you also want press mentions or do they go elsewhere? 

"In-toto: providing farm-to-table guarantees for bits and bytes" (press coverage related to in-toto) Article
The Morning Paper, October 2019.

"33(+) Kubernetes security tools" (press coverage related to in-toto and TUF/Notary) Article
Sysdig Blog, July 2019.

 If you want a verision w/ links (just search for in-toto here): 
 https://ssl.engineering.nyu.edu/personalpages/jcappos/press.htm

**Comment by lukpueh** [comment]
Thanks for the pointers @JustinCappos I added them to the news section.

**Comment by SantiagoTorres** [comment]
Hi @lukpueh , it appears to me the FAQ creeped into this PR?

**Comment by lukpueh** [comment]
Thanks for catching the git history hiccup, @SantiagoTorres! I dropped the obsolete commit, rebased, force-pushed and threw in an unrelated fix. :)

**Comment by SantiagoTorres** [comment]
Thank you! @lukpueh

**Pull request merged**
